---
- block:
    - name: remove packages
      apt:
        name: "{{ common_console_nosetup__unwanted_packages |to_package_list }}"
        state: absent
        purge: yes
  when: ansible_distribution == 'Debian'

- name: ensure grub.d
  file:
    state: directory
    path:  /etc/default/grub.d
    mode:  0755
    owner: root
    group: root

- name: add a config file
  copy:
    content: >
      GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX nomodeset"
    dest: /etc/default/grub.d/99-nomodeset.cfg
    mode:  0644
    owner: root
    group: root
  notify: update-grub
