---
- name: ensure grub.d
  file:
    state: directory
    path:  /etc/default/grub.d
    mode:  0755
    owner: root
    group: root

# FIXME: check /etc/network/interfaces for eth*

- name: add a config file
  copy:
    content: >
      GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX net.ifnames=0"
    dest: /etc/default/grub.d/99-net.ifnames.cfg
    mode:  0644
    owner: root
    group: root
  notify: update-grub
