---
- include_tasks: "steps/{{ tinc__v_install_loop.step }}.yml"
  when: tinc__v_install_loop.condition == true
  with_items:
    - { step: '0_user',                      condition: "{{ not tinc__fast_configure }}" }
    - { step: '1_systemd',                   condition: "{{ not tinc__fast_configure }}" }
    - { step: '2_packages',                  condition: "{{ not tinc__fast_configure }}" }
    - { step: '3_config',                    condition: true }
  loop_control:
    loop_var: tinc__v_install_loop
