---
- include_tasks: try_fstrim.yml
  vars:
    common_fstrim__mount_to_try: "{{ item.mount }}"
  when: not ansible_check_mode
  with_items: "{{ ansible_mounts }}"

- include_tasks: task_systemd.yml
  when: (ansible_service_mgr == 'systemd') and (common_fstrim__supported != {})

- include_tasks: task_cron.yml
  when: (ansible_service_mgr != 'systemd') and (common_fstrim__supported != {})
