---

# remove the crap
- name: patch perl module
  replace:
    path: "{{ proxmox__cluster_pm_path }}"
    regexp: "return if\\s+.*PermitRootLogin.*;$"
    replace: "return;"
    backup: yes
  failed_when: false

- name: fix things
  replace:
    path: /etc/ssh/sshd_config
    regexp: '(?i)^\s*PermitRootLogin\s+yes.*$'
    replace: 'PermitRootLogin prohibit-password'
  notify: reload ssh.service
