---
- name: fix permissions
  file:
    path:  "{{ nsd__conf_dir }}"
    state: directory
    owner: root
    group: "{{ nsd__group }}"
    mode:  'g+rX,o-rwx'
    recurse: yes

- name: install config
  template:
    src:    nsd.conf.j2
    dest:   "{{ nsd__conf_dir }}/nsd.conf"
    backup: yes
    owner:  root
    group:  "{{ nsd__group }}"
    mode:   0640
  notify: restart nsd.service
