---
- name: remove repo
  apt_repository:
    repo: "deb {{ item }} {{ ansible_distribution_release }} pve-enterprise"
    state: absent
  with_items:
    - 'https://enterprise.proxmox.com/debian/pve'
    - 'https://enterprise.proxmox.com/debian'

- name: check pve-manager version
  pkg_check:
    name: pve-manager
  register: proxmox_noenterprise__v_package

# https://www.jamescoyle.net/how-to/614-remove-the-proxmox-no-subscription-message
- name: patch JS
  replace:
    path: "{{ proxmox_noenterprise__js_path }}"
    regexp: "if \\(data\\.status !== 'Active'\\) \\{"
    replace: "if (false) {"
    backup: yes
  when: proxmox_noenterprise__v_package.installed
