---
- include_role:
    name: common_apt
  vars:
    common_apt__extra_repos:
      debian_experimental:
        install: true
        preferences:
          tinc:
            packages: "tinc"
            priority: 500

- name: install packages
  apt:
    name: "{{ tinc__required_packages |to_package_list }}"
    update_cache: yes
    state: present
