---
# https://github.com/systemd/systemd/issues/6281

- name: change tincd permissions
  file:
    state: file
    path:  "{{ tinc__binary }}"
    owner: root
    group: "{{ tinc__group }}"
    mode:  0750

- name: change tincd capabilities
  capabilities:
    path:       "{{ tinc__binary }}"
    capability: "{{ item }}"
  with_items:
    - cap_net_bind_service+ep
    - cap_net_admin+ep
    - cap_ipc_lock+ep

- name: install daemontools
  apt:
    name: daemontools

- name: create {{ tinc__lib_dir }}
  file:
    state: directory
    path:  "{{ tinc__lib_dir }}"
    owner: root
    group: "{{ tinc__group }}"
    mode:  0750

- stat:
    path: "{{ tinc__ip_binary_orig }}"
  register: tinc__v_ip_binary_orig

- stat:
    path: "{{ tinc__ip_binary_local }}"
  register: tinc__v_ip_binary_local

- name: copy local version of ip
  copy:
    remote_src: yes
    src:        "{{ tinc__ip_binary_orig }}"
    dest:       "{{ tinc__ip_binary_local }}"
    owner:      root
    group: "{{ tinc__group }}"
    mode:  0750
  when: not tinc__v_ip_binary_local.stat.exists or tinc__v_ip_binary_local.stat.checksum != tinc__v_ip_binary_orig.stat.checksum

- name: change ip capabilities
  capabilities:
    path:       "{{ tinc__ip_binary_local }}"
    capability: 'cap_net_admin+ep'
