---
- name: "{{ tinc__v_config_net_name }} | update host config"
  template:
    src:    host.conf.j2
    dest:   "{{ tinc__v_config_net_base }}/hosts/{{ tinc__v_net_hosts_loop.value.host_name }}"
    owner:  "{{ tinc__user }}"
    group:  "{{ tinc__group }}"
    mode:   0600
    backup: no
  notify: restart tinc.target
  with_dict: "{{ tinc__v_peers.data[tinc__v_config_net_name] }}"
  loop_control:
    loop_var: tinc__v_net_hosts_loop
