---
# do a black magic to make internal web server work

- name: read symlink
  stat: { path: "{{ certbot__python_exe }}" }
  register: certbot__v_python_exe_stat

- name:
  set_fact:
    certbot__v_python_exe_orig:   "{{ certbot__v_python_exe_stat.stat.lnk_source }}"
    certbot__v_python_exe_to_use: "{{ certbot__v_python_exe_stat.stat.lnk_source }}_certbot"

- name: copy python executable
  copy:
    src:  "{{ certbot__v_python_exe_orig }}"
    dest: "{{ certbot__v_python_exe_to_use }}"
    remote_src: true
    owner: "{{ certbot__user }}"
    group: "{{ certbot__group }}"
    mode:  0700

- name: add cap_net_bind_service to python executable
  capabilities:
    path: "{{ certbot__v_python_exe_to_use }}"
    capability: cap_net_bind_service+ep
