---
- name: create systemd unit
  template:
    src:    ipv6-duid.service.j2
    dest:   /etc/systemd/system/ipv6-duid.service
    backup: yes
    owner:  root
    group:  root
    mode:   0644
  notify: restart ipv6-duid.service

- systemd:
    unit: ipv6-duid.service
    daemon_reload: yes
    enabled: yes
