---
memcached__required_packages:
  memcached: true

memcached__mem_default: 0.10
memcached__loopback_default: true

memcached__instances: {}
#  11211:
#    loopback: false
#    mem:      0.15
#  11212:
#    loopback: true
#    mem:      0.32
