---
- include_tasks: "steps/{{ prometheus_node_exporter__yml_loop }}.yml"
  with_items:
    - '0_packages'
    - '1_configs'
    - '2_scripts'
    - '3_static_metrics'
  loop_control:
    loop_var: prometheus_node_exporter__yml_loop
