---
- name: install config
  copy:
    content: "{{ prometheus__conf_content }}"
    dest:    "{{ prometheus__conf_path }}"
    mode:    0640
    owner:   root
    group:   "{{ prometheus__group }}"
    backup:  yes
  notify: reload prometheus
