---
- name: "get {{ common_users__v_user }}'s pw"
  get_pw:
    user: "{{ common_users__v_user }}"
  register: common_users__v_pw

- name: create ~{{ common_users__v_user }}/.ssh/
  file:
    path:  "{{ common_users__v_pw.pw.dir }}/.ssh"
    state: directory
    mode:  0700
  become_user: "{{ common_users__v_user }}"

- block:
    - proxmox_facts:
      when: ansible_virtualization_role == 'host'

    - name: read proxmox local SSH keys
      shell: cat id_*.pub
      args:
        chdir: "{{ common_users__v_pw.pw.dir }}/.ssh"
      failed_when: false
      changed_when: false
      become_user: "{{ common_users__v_user }}"
      register: common_users__v_local_ssh_keys
      when: not (proxmox_facts |is_empty_or_undefined)
  when: common_users__v_user == 'root'

- name: converge authorized_keys for {{ item.key }}
  template:
    src:    authorized_keys.j2
    dest:   "{{ common_users__v_pw.pw.dir }}/.ssh/authorized_keys"
    backup: yes
    mode:   0600
  become_user: "{{ common_users__v_user }}"
