---
- name: install config
  template:
    src:     defaults.j2
    dest:    "{{ prometheus_node_exporter__conf_path }}"
    mode:    0644
    owner:   root
    group:   root
    backup:  yes
  notify: restart prometheus_node_exporter

- name: fix textfile dir permissions
  file:
    state: directory
    path:  "{{ prometheus_node_exporter__textfile_path }}"
    mode:  0755
    owner: "{{ prometheus_node_exporter__user }}"
    group: "{{ prometheus_node_exporter__group }}"
