---
- name: add node_fqdn
  node_set_metric:
    name:       'fqdn'
    content:    "{{ ansible_fqdn }}"
    help_text:  "Node FQDN"
  become_user: "{{ prometheus_node_exporter__user }}"

- name: try to fetch AWS-style location
  command: curl -m 1 -s http://169.254.169.254/latest/meta-data/placement/availability-zone
  args:
    warn: false
  failed_when: false
  changed_when: false
  register: prometheus_node_exporter__v_location

- name: add node_location_dc
  node_set_metric:
    name:       'location_dc'
    content:    "{{ prometheus_node_exporter__v_location.stdout }}"
    help_text:  "Node location (Datacenter)"
  become_user: "{{ prometheus_node_exporter__user }}"
  when: (prometheus_node_exporter__v_location.rc == 0) and (prometheus_node_exporter__v_location.stdout != "")
